export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESFULL = "PRODUCT_SUCCESFULL";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_DETAIL_SUCCESFULL = "PRODUCT_SUCCESFULL";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_FAIL";
